import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/home/navbar";
import ApolloProvider from "@/providers/clientProvider/apolloProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import ThemeProvider from "@/providers/clientProvider/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <AppRouterCacheProvider>
          <ApolloProvider>
            <ThemeProvider>
              {" "}
              <Navbar />
              {children}
            </ThemeProvider>
          </ApolloProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
